# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8d72af05da537fba6704b1edb56af86a45352de3010e57983cd253e472f34cae0ebeccaf4d647509b724796cc8cda76cd35f7eee55f8b08c6325fc4a27f933f

test:
  secret_key_base: 13dbc144adaab9c74e0f310c782371f9cbf841c9385d6c3d89ca1b4e09c84c34657177271b46e17bc97ebbe340a89be482d7147d5db71c5b847e1b39a412bf48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
